<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="PRG_PLC1" Id="{008ff7e3-702c-4b23-834b-f8aafcce3fa4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_PLC1
VAR
	ToPLC_X	  AT %Q* : UDINT;
	
	FromPLC2  AT %I*  :UDINT;
	FromPLC3  AT %I*  :UDINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_ConsumeTime(5);
ToPLC_X := (ToPLC_X + 1) MOD 200;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>