<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="PRG_PLC3" Id="{b8a8887f-b6db-4664-83a4-18109ba30a82}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_PLC3
VAR
	ToPLC_X	  AT %Q* : UDINT;
	FromPLC1  AT %I*  :UDINT;
	FromPLC2  AT %I*  :UDINT;		
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_ConsumeTime(5);
ToPLC_X := (ToPLC_X + 1) MOD 200;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>