<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="MAIN" Id="{46c6155e-1631-4f07-9de1-af6d71d4f845}" SpecialFunc="None">
    <Declaration><![CDATA[//Provider PLC
PROGRAM MAIN
VAR
	DelayToCallInterface : UDINT := 10;
	fbDoWork			 : FB_DoWork('MAIN.fbDoWork');
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_ConsumeTime(DelayToCallInterface);
fbDoWork.M_Increment();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>