///////////////////////////////////////////////////////////////////////////////
// cppServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_cpp = 0x3F000000;
#define SRVNAME_CPP "cpp"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_cppCModule1 = {0xe3b3eaf2,0xb0aa,0x4f70,{0xb9,0x3a,0x8f,0x5b,0x0d,0xd9,0x43,0x2c}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Outputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Module1Data = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Outputs
{
	ULONG Value;
	BYTE Data[150000];
} Module1Outputs, *PModule1Outputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
