<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="PRG_PLC2" Id="{cce961d7-e523-4b2f-ba28-fed189464f30}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_PLC2
VAR
	EncoderValue AT %I* : UINT;
	Pos					: LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_ConsumeTime(20);

Pos:= UINT_TO_LREAL(EncoderValue)*100;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>