///////////////////////////////////////////////////////////////////////////////
// cppClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "cppClassFactory.h"
#include "cppServices.h"
#include "cppVersion.h"
#include "Module1.h"

BEGIN_CLASS_MAP(CcppClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_cpp, CID_cppCModule1, SRVNAME_CPP "!CModule1", CModule1)
///</AutoGeneratedContent>
END_CLASS_MAP()

CcppClassFactory::CcppClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_CPP));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(cpp));
#endif //defined(TCDBG_UNIT_VERSION)
}

