///////////////////////////////////////////////////////////////////////////////
// cppServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_cpp = 0x3F000000;
#define SRVNAME_CPP "cpp"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_cppCModule1 = {0xaf3b890b,0xab8a,0x4890,{0x82,0x1a,0x87,0x9f,0x3e,0x9e,0x0a,0x3d}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Inputs 0
#define ADI_Module1Outputs 1
#define ADI_Module1Internal 3
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Inputs
{
	ULONG Counter1;
	ULONG Counter2;
} Module1Inputs, *PModule1Inputs;

typedef struct _Module1Outputs
{
	ULONG ToX;
} Module1Outputs, *PModule1Outputs;

typedef struct _Module1Internal
{
	ULONG Counter1;
	ULONG Counter2;
} Module1Internal, *PModule1Internal;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
